<?php 

/**
 * Get the score of a page.
 * 
 * @param array $data The data of the page generated by WILO.
 */
function wilo_get_internal_linking_score($data){

    $score = 0;

    if($data['incoming_internal_links_count'] > 15):
        $score = 100;
    elseif($data['incoming_internal_links_count'] > 14):
        $score = 95;
    elseif($data['incoming_internal_links_count'] > 13):
        $score = 90;
    elseif($data['incoming_internal_links_count'] > 12):
        $score = 85;
    elseif($data['incoming_internal_links_count'] > 11):
        $score = 80;
    elseif($data['incoming_internal_links_count'] > 10):
        $score = 75;
    elseif($data['incoming_internal_links_count'] > 9):
        $score = 70;
    elseif($data['incoming_internal_links_count'] > 8):
        $score = 65;
    elseif($data['incoming_internal_links_count'] > 7):
        $score = 60;
    elseif($data['incoming_internal_links_count'] > 6):
        $score = 55;
    elseif($data['incoming_internal_links_count'] > 5):
        $score = 50;
    elseif($data['incoming_internal_links_count'] > 4):
        $score = 45;
    elseif($data['incoming_internal_links_count'] > 3):
        $score = 40;
    elseif($data['incoming_internal_links_count'] > 2):
        $score = 35;
    elseif($data['incoming_internal_links_count'] > 1):
        $score = 30;
    elseif($data['incoming_internal_links_count'] > 0):
        $score = 25;
    else:
        $score = 0;
    endif;

    if($score > 100):
        $score = 100;
    endif;

    if($data['duplicate_anchors_count'] > 10):
        $score = $score - 25;
    elseif($data['duplicate_anchors_count'] > 9):
        $score = $score - 23;
    elseif($data['duplicate_anchors_count'] > 8):
        $score = $score - 22;
    elseif($data['duplicate_anchors_count'] > 7):
        $score = $score - 21;
    elseif($data['duplicate_anchors_count'] > 6):
        $score = $score - 19;
    elseif($data['duplicate_anchors_count'] > 5):
        $score = $score - 17;
    elseif($data['duplicate_anchors_count'] > 4):
        $score = $score - 15;
    elseif($data['duplicate_anchors_count'] > 3):
        $score = $score - 12;
    elseif($data['duplicate_anchors_count'] > 2):
        $score = $score - 9;
    elseif($data['duplicate_anchors_count'] > 1):
        $score = $score - 5;
    endif;

    if($data['stuffed_links'] > 10):
        $score = $score - 25;
    elseif($data['stuffed_links'] > 9):
        $score = $score - 23;
    elseif($data['stuffed_links'] > 8):
        $score = $score - 22;
    elseif($data['stuffed_links'] > 7):
        $score = $score - 20;
    elseif($data['stuffed_links'] > 6):
        $score = $score - 19;
    elseif($data['stuffed_links'] > 5):
        $score = $score - 17;
    elseif($data['stuffed_links'] > 4):
        $score = $score - 15;
    elseif($data['stuffed_links'] > 3):
        $score = $score - 12;
    elseif($data['stuffed_links'] > 2):
        $score = $score - 9;
    elseif($data['stuffed_links'] > 1):
        $score = $score - 5;
    endif;

    if($score < 1):
        $score = 1;
    endif;

    $score = round($score, 0);

    return $score;


} ?>